[package]
name = "tfg_project"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
rustls = { version = "0.23.31", default-features = false, features = ["aws_lc_rs", "std", "logging", "prefer-post-quantum"] }
rustls-pemfile = "2.2.0"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.52.4", features = ["full"] }
tokio-rustls = "0.26.4"
webpki-roots = "1"
tokio-util = { version = "0.7", features = ["rt"] }
hyper-util = { version = "0.1", features = ["tokio"] }
hyper = { version = "1", features = ["http1"] }
tower-http = { version = "0.6", features = ["fs", "cors"] }
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio", "macros", "uuid", "migrate"]}
uuid = { version = "1", features = ["v4", "serde"] }
bollard = "0.21"
http-body-util = "0.1.4"
serde_json = "1.0.151"
http = "1.1"
reqwest = { version = "0.12", features = ["json", "stream", "rustls-tls"] }
bytes = "1.12.1"
chrono = "0.4.45"
futures-util = "0.3.34"

[[bin]]
name = "application"
path = "src/application_main.rs"

[[bin]]
name = "tfg_dashboard"
path = "src/main.rs"

[[bin]]
name = "tfg_server"
path = "src/server/server_main.rs"

[[bin]]
name = "tfg_client"
path = "src/client/client_main.rs"
