FROM rust:1.88 AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY migrations ./migrations
RUN cargo build --release --bin tfg_dashboard
FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y \
    libssl-dev ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/tfg_dashboard .
COPY simplified-pki ./simplified-pki
COPY src/dashboard/ui ./src/dashboard/ui
CMD ["./tfg_dashboard"]