name: secure_crypt

services:

  postgres:
    image: postgres:16
    container_name: securecrypt-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securecrypt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: securecrypt-dashboard
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/securecrypt
      TIME_ZONE: Europe/Madrid
      APPLICATION_URL: https://127.0.0.1:8443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./simplified-pki:/app/simplified-pki
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: secure_crypt_postgres_data